#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GREEN='\033[0;32m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; NC='\033[0m'
info()  { printf "${GREEN}[INFO]${NC}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
error() { printf "${RED}[ERROR]${NC} %s\n" "$*"; }

show_help() {
  cat <<'EOF'
Usage: init.sh --app-name APP_NAME [OPTIONS]

Scaffold a new application. Creates the app directory with .env config
and optionally a Dockerfile and source files. Optionally runs the build.

Required:
  --app-name NAME       Application name (k8s-safe: lowercase, hyphens only)

Options:
  --dockerfile TYPE    Scaffold a sample Dockerfile (go|python|node|none)
                       (default: none)
  --registry-url URL   Container registry hostname (default: localhost)
  --registry-port PORT Container registry port (default: 50000)
  --k8s-ns NS   Kubernetes namespace (default: apps-ns)
  --container-port PORT App port (default: 8080)
  --build             Run build.sh after scaffolding (build + push)
  --deploy            Run build.sh --auto-deploy after scaffolding
  --image-tag TAG     Docker image tag for --build/--deploy (default: v1.0)
  --help               Show this help message

Examples:
  ./init.sh --app-name my-api
  ./init.sh --app-name my-api --dockerfile go
  ./init.sh --app-name my-api --dockerfile go --build
  ./init.sh --app-name my-api --build --deploy
EOF
  exit 0
}

# ── Parse args ──────────────────────────────────────────────
APP_NAME=""
DOCKERFILE_TYPE="none"
REGISTRY_URL="localhost"
REGISTRY_PORT="50000"
K8S_NAMESPACE="apps-ns"
CONTAINER_PORT="8080"
RUN_BUILD=false
RUN_DEPLOY=false
IMAGE_TAG="v1.0"

while [ $# -gt 0 ]; do
  case "$1" in
    --help)              show_help ;;
    --app-name)          APP_NAME="$2"; shift 2 ;;
    --app-name=*)        APP_NAME="${1#*=}"; shift ;;
    --dockerfile)        DOCKERFILE_TYPE="$2"; shift 2 ;;
    --dockerfile=*)      DOCKERFILE_TYPE="${1#*=}"; shift ;;
    --registry-url)      REGISTRY_URL="$2"; shift 2 ;;
    --registry-url=*)    REGISTRY_URL="${1#*=}"; shift ;;
    --registry-port)     REGISTRY_PORT="$2"; shift 2 ;;
    --registry-port=*)   REGISTRY_PORT="${1#*=}"; shift ;;
    --k8s-ns)     K8S_NAMESPACE="$2"; shift 2 ;;
    --k8s-ns=*)   K8S_NAMESPACE="${1#*=}"; shift ;;
    --container-port)    CONTAINER_PORT="$2"; shift 2 ;;
    --container-port=*)  CONTAINER_PORT="${1#*=}"; shift ;;
    --build)             RUN_BUILD=true; shift ;;
    --deploy)            RUN_DEPLOY=true; RUN_BUILD=true; shift ;;
    --image-tag)         IMAGE_TAG="$2"; shift 2 ;;
    --image-tag=*)       IMAGE_TAG="${1#*=}"; shift ;;
    -h)                  show_help ;;
    *)
      error "Unknown argument: $1"
      exit 1
      ;;
  esac
done

if [ -z "$APP_NAME" ]; then
  error "--app-name is required"
  exit 1
fi

if ! echo "$APP_NAME" | grep -qE '^[a-z][a-z0-9-]*$'; then
  error "App name must be k8s-safe: start with a letter, only lowercase alphanumeric and hyphens"
  exit 1
fi

TARGET_DIR="$(dirname "$PWD")/$APP_NAME"

# ── Create app directory ────────────────────────────────────
if [ -d "$TARGET_DIR" ]; then
  info "App directory exists — updating .env and templates"
else
  info "Creating $APP_NAME..."
  mkdir -p "$TARGET_DIR"
fi

cd "$TARGET_DIR" || exit 1

# ── Write .env (with user-provided values) ──────────────────
cat > .env <<EOF
# Generated by init.sh — customize as needed
APP_NAME=$APP_NAME
GIT_REPO_BASE=https://github.com/natanbs
REGISTRY_URL=$REGISTRY_URL
REGISTRY_PORT=$REGISTRY_PORT
REGISTRY_CLUSTER_URL=k3d-reg
REGISTRY_CLUSTER_PORT=5000
K8S_NAMESPACE=$K8S_NAMESPACE
CONTAINER_PORT=$CONTAINER_PORT
EOF
info "Wrote .env"

# ── Write .gitignore ────────────────────────────────────────
cp "$SCRIPT_DIR/gitignore" .gitignore
info "Wrote .gitignore"

# ── Copy language-specific scaffolds ────────────────────────
case "$DOCKERFILE_TYPE" in
  go|python|node)
    if [ -d "$SCRIPT_DIR/$DOCKERFILE_TYPE" ]; then
      for f in "$SCRIPT_DIR/$DOCKERFILE_TYPE"/*; do
        [ -f "$f" ] || continue
        cp -n "$f" ./ 2>/dev/null || true
      done
      info "Scaffolded $DOCKERFILE_TYPE Dockerfile + source files"
    fi
    ;;
  none)
    info "No Dockerfile scaffolded (add your own)"
    ;;
  *)
    warn "Unknown dockerfile type '$DOCKERFILE_TYPE' — skipping"
    ;;
esac

# ── git init (only for new directories) ─────────────────────
if [ ! -d .git ]; then
  git init
  git add .
  git commit -m "Initial scaffold" >/dev/null 2>&1 || true
  info "Initialized git repository"
fi

# ── Ensure namespace exists ─────────────────────────────────
if command -v kubectl &>/dev/null && kubectl cluster-info 2>/dev/null >/dev/null; then
  kubectl create namespace "$K8S_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  info "Ensured namespace '$K8S_NAMESPACE' exists on cluster"
else
  warn "No cluster reachable — skipping namespace creation"
fi

# ── Run build if requested ──────────────────────────────────
if [ "$RUN_BUILD" = true ]; then
  if [ -x "$SCRIPT_DIR/../build.sh" ]; then
    "$SCRIPT_DIR/../build.sh" --app-name "$APP_NAME" --image-tag "$IMAGE_TAG"
    BUILD_STATUS=$?
  else
    warn "build.sh not found in parent directory — skipping build"
    BUILD_STATUS=1
  fi

  if [ "$RUN_DEPLOY" = true ] && [ "$BUILD_STATUS" -eq 0 ]; then
    if [ -x "$SCRIPT_DIR/../build.sh" ]; then
      "$SCRIPT_DIR/../build.sh" --app-name "$APP_NAME" --image-tag "$IMAGE_TAG" --auto-deploy
    else
      warn "build.sh not found in parent directory — skipping deploy"
    fi
  fi
fi

# ── Summary ──────────────────────────────────────────────────
echo
step() { printf "\n${CYAN}=== %s ===${NC}\n" "$*"; }
step "Scaffold complete"
echo
echo "  Directory: $TARGET_DIR"
echo "  App name:  $APP_NAME"
echo "  Registry:  $REGISTRY_URL:$REGISTRY_PORT"
echo "  Namespace: $K8S_NAMESPACE"
echo
if [ "$RUN_BUILD" = false ]; then
  echo "Next steps:"
  echo "  cd ../$APP_NAME"
  echo "  ../gitops-template/build.sh --app-name $APP_NAME --image-tag v1.0"
  echo "  ../gitops-template/build.sh --app-name $APP_NAME --image-tag v1.0 --auto-deploy"
fi
echo
