#!/usr/bin/env bash
set -euo pipefail

TEMPLATE_REPO="https://github.com/natanbs/gitops-template.git"

GREEN='\033[0;32m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; NC='\033[0m'
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
info()  { printf "${GREEN}[INFO]${NC}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
error() { printf "${RED}[ERROR]${NC} %s\n" "$*"; }

show_help() {
  cat <<'EOF'
Usage: init.sh --app-name APP_NAME [OPTIONS]

Scaffold a new application from the gitops-template.

By default clones from the remote template repository. Use --repo-url
to specify a different remote, or --local to copy the local directory.

Required:
  --app-name NAME       Application name (k8s-safe: lowercase, hyphens only)

Options:
  --dockerfile TYPE    Scaffold a sample Dockerfile (go|python|node|none)
                       (default: none)
  --repo-url URL       Remote git repository URL
                       (default: https://github.com/natanbs/gitops-template.git)
  --local              Copy local template instead of cloning from remote
  --registry-url URL   Container registry hostname (default: localhost)
  --registry-port PORT Container registry port (default: 50000)
  --k8s-ns NS   Kubernetes namespace (default: apps-ns)
  --container-port PORT App port (default: 8080)
  --help               Show this help message

Examples:
  ./init.sh --app-name my-api
  ./init.sh --app-name my-api --dockerfile go
  ./init.sh --app-name my-api --dockerfile python --container-port 9000
  ./init.sh --app-name my-api --local  # copy from local working tree
EOF
  exit 0
}

# ── Parse args ──────────────────────────────────────────────
APP_NAME=""
DOCKERFILE_TYPE="none"
REPO_URL=""
REGISTRY_URL="localhost"
REGISTRY_PORT="50000"
K8S_NAMESPACE="apps-ns"
CONTAINER_PORT="8080"

while [ $# -gt 0 ]; do
  case "$1" in
    --help)              show_help ;;
    --app-name)          APP_NAME="$2"; shift 2 ;;
    --app-name=*)        APP_NAME="${1#*=}"; shift ;;
    --dockerfile)        DOCKERFILE_TYPE="$2"; shift 2 ;;
    --dockerfile=*)      DOCKERFILE_TYPE="${1#*=}"; shift ;;
    --repo-url)          REPO_URL="$2"; shift 2 ;;
    --repo-url=*)        REPO_URL="${1#*=}"; shift ;;
    --local)             REPO_URL="local"; shift ;;
    --registry-url)      REGISTRY_URL="$2"; shift 2 ;;
    --registry-url=*)    REGISTRY_URL="${1#*=}"; shift ;;
    --registry-port)     REGISTRY_PORT="$2"; shift 2 ;;
    --registry-port=*)   REGISTRY_PORT="${1#*=}"; shift ;;
    --k8s-ns)     K8S_NAMESPACE="$2"; shift 2 ;;
    --k8s-ns=*)   K8S_NAMESPACE="${1#*=}"; shift ;;
    --container-port)    CONTAINER_PORT="$2"; shift 2 ;;
    --container-port=*)  CONTAINER_PORT="${1#*=}"; shift ;;
    -h)                  show_help ;;
    *)
      error "Unknown argument: $1"
      exit 1
      ;;
  esac
done

if [ -z "$APP_NAME" ]; then
  error "--app-name is required"
  exit 1
fi

if ! echo "$APP_NAME" | grep -qE '^[a-z][a-z0-9-]*$'; then
  error "App name must be k8s-safe: start with a letter, only lowercase alphanumeric and hyphens"
  exit 1
fi

TARGET_DIR="$(dirname "$PWD")/$APP_NAME"

# ── Clone or copy template ──────────────────────────────────
if [ -d "$TARGET_DIR" ]; then
  error "Directory '$TARGET_DIR' already exists"
  exit 1
fi

if [ "$REPO_URL" = "local" ]; then
  info "Copying local template to $APP_NAME..."
  mkdir -p "$TARGET_DIR"
  rsync -a --exclude='.git' "$SCRIPT_DIR/" "$TARGET_DIR/"
else
  REPO_URL="${REPO_URL:-$TEMPLATE_REPO}"
  info "Cloning template from $REPO_URL..."
  git clone "$REPO_URL" "$TARGET_DIR"
fi

cd "$TARGET_DIR"

info "Initializing fresh git history..."
rm -rf .git
git init
git add .
git commit -m "Initial scaffold from gitops-template" >/dev/null

# ── Write .env ──────────────────────────────────────────────
cat > .env <<EOF
# Generated by init.sh — customize as needed
APP_NAME=$APP_NAME
REGISTRY_URL=$REGISTRY_URL
REGISTRY_PORT=$REGISTRY_PORT
K8S_NAMESPACE=$K8S_NAMESPACE
CONTAINER_PORT=$CONTAINER_PORT
EOF

info "Wrote .env with project defaults"

# ── Scaffold Dockerfile ─────────────────────────────────────
case "$DOCKERFILE_TYPE" in
  go)
    cat > Dockerfile <<'DOCKER'
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY main.go .
RUN go build -o server main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE ${CONTAINER_PORT}
CMD ["./server"]
DOCKER
    cat > main.go <<'GO'
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello from Go!")
	})
	http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
	http.HandleFunc("/readyz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
	http.ListenAndServe(":8080", nil)
}

func port() string {
	return "8080"
}
GO
    info "Scaffolded Go Dockerfile + main.go"
    ;;

  python)
    cat > Dockerfile <<'DOCKER'
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
EXPOSE ${CONTAINER_PORT}
CMD ["python", "app.py"]
DOCKER
    cat > requirements.txt <<'EOF'
flask==3.0.0
EOF
    cat > app.py <<'EOF'
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello from Python!"

@app.route("/healthz")
def healthz():
    return "ok", 200

@app.route("/readyz")
def readyz():
    return "ok", 200

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
EOF
    info "Scaffolded Python Flask Dockerfile + app.py"
    ;;

  node)
    cat > Dockerfile <<'DOCKER'
FROM node:20-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY server.js .
EXPOSE ${CONTAINER_PORT}
CMD ["node", "server.js"]
DOCKER
    cat > package.json <<'EOF'
{
  "name": "my-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node server.js"
  }
}
EOF
    cat > server.js <<'EOF'
const http = require("http");
const port = process.env.PORT || 8080;
const server = http.createServer((req, res) => {
  if (req.url === "/healthz" || req.url === "/readyz") {
    res.writeHead(200);
    return res.end("ok");
  }
  res.writeHead(200, { "Content-Type": "text/plain" });
  res.end("Hello from Node.js!");
});
server.listen(port, () => console.log(`Listening on ${port}`));
EOF
    info "Scaffolded Node.js Dockerfile + server.js"
    ;;

  none|*)
    info "No Dockerfile scaffolded (add your own)"
    ;;
esac

git add .
git commit -m "Add project files" >/dev/null 2>&1 || true

# ── Ensure namespace exists ─────────────────────────────────
if command -v kubectl &>/dev/null && kubectl cluster-info 2>/dev/null >/dev/null; then
  kubectl create namespace "$K8S_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  info "Ensured namespace '$K8S_NAMESPACE' exists on cluster"
else
  warn "No cluster reachable — skipping namespace creation"
fi

# ── Summary ──────────────────────────────────────────────────
echo
step() { printf "\n${CYAN}=== %s ===${NC}\n" "$*"; }
step "Scaffold complete"
echo
echo "  Directory: $TARGET_DIR"
echo "  App name:  $APP_NAME"
echo "  Registry:  $REGISTRY_URL:$REGISTRY_PORT"
echo "  Namespace: $K8S_NAMESPACE"
echo
echo "Next steps:"
echo "  cd ../$APP_NAME"
echo "  ./build.sh --image-tag v1.0"
echo "  ./build.sh --image-tag v1.0 --auto-deploy"
echo
