#!/usr/bin/env bash
set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[0;33m'; CYAN='\033[0;36m'; RED='\033[0;31m'; NC='\033[0m'
info()  { printf "${GREEN}[INFO]${NC}  %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
error() { printf "${RED}[ERROR]${NC} %s\n" "$*"; }

show_help() {
  cat <<'EOF'
Usage: init.sh --app-name APP_NAME [OPTIONS]

Scaffold a new application. Creates the app directory with .env config
and optionally a Dockerfile and source files. Optionally runs the build.

Required:
  --app-name NAME       Application name (k8s-safe: lowercase, hyphens only)

Options:
  --dockerfile TYPE    Scaffold a sample Dockerfile (go|python|node|none)
                       (default: none)
  --registry-url URL   Container registry hostname (default: localhost)
  --registry-port PORT Container registry port (default: 50000)
  --k8s-ns NS   Kubernetes namespace (default: apps-ns)
  --container-port PORT App port (default: 8080)
  --build             Run build.sh after scaffolding (build + push)
  --deploy            Run build.sh --auto-deploy after scaffolding
  --image-tag TAG     Docker image tag for --build/--deploy (default: v1.0)
  --help               Show this help message

Examples:
  ./init.sh --app-name my-api
  ./init.sh --app-name my-api --dockerfile go
  ./init.sh --app-name my-api --dockerfile go --build
  ./init.sh --app-name my-api --build --deploy
EOF
  exit 0
}

# ── Parse args ──────────────────────────────────────────────
APP_NAME=""
DOCKERFILE_TYPE="none"
REGISTRY_URL="localhost"
REGISTRY_PORT="50000"
K8S_NAMESPACE="apps-ns"
CONTAINER_PORT="8080"
RUN_BUILD=false
RUN_DEPLOY=false
IMAGE_TAG="v1.0"

while [ $# -gt 0 ]; do
  case "$1" in
    --help)              show_help ;;
    --app-name)          APP_NAME="$2"; shift 2 ;;
    --app-name=*)        APP_NAME="${1#*=}"; shift ;;
    --dockerfile)        DOCKERFILE_TYPE="$2"; shift 2 ;;
    --dockerfile=*)      DOCKERFILE_TYPE="${1#*=}"; shift ;;
    --registry-url)      REGISTRY_URL="$2"; shift 2 ;;
    --registry-url=*)    REGISTRY_URL="${1#*=}"; shift ;;
    --registry-port)     REGISTRY_PORT="$2"; shift 2 ;;
    --registry-port=*)   REGISTRY_PORT="${1#*=}"; shift ;;
    --k8s-ns)     K8S_NAMESPACE="$2"; shift 2 ;;
    --k8s-ns=*)   K8S_NAMESPACE="${1#*=}"; shift ;;
    --container-port)    CONTAINER_PORT="$2"; shift 2 ;;
    --container-port=*)  CONTAINER_PORT="${1#*=}"; shift ;;
    --build)             RUN_BUILD=true; shift ;;
    --deploy)            RUN_DEPLOY=true; RUN_BUILD=true; shift ;;
    --image-tag)         IMAGE_TAG="$2"; shift 2 ;;
    --image-tag=*)       IMAGE_TAG="${1#*=}"; shift ;;
    -h)                  show_help ;;
    *)
      error "Unknown argument: $1"
      exit 1
      ;;
  esac
done

if [ -z "$APP_NAME" ]; then
  error "--app-name is required"
  exit 1
fi

if ! echo "$APP_NAME" | grep -qE '^[a-z][a-z0-9-]*$'; then
  error "App name must be k8s-safe: start with a letter, only lowercase alphanumeric and hyphens"
  exit 1
fi

TARGET_DIR="$(dirname "$PWD")/$APP_NAME"

# ── Create app directory ────────────────────────────────────
if [ -d "$TARGET_DIR" ]; then
  error "Directory '$TARGET_DIR' already exists"
  exit 1
fi

info "Creating $APP_NAME..."
mkdir -p "$TARGET_DIR"

# ── Write .gitignore ────────────────────────────────────────
cat > "$TARGET_DIR/.gitignore" <<'EOF'
# Generated K8s manifests (output from envsubst via build.sh)
k8s/*.yaml

# Generated ArgoCD manifests
argocd/*.yaml

# OS files
.DS_Store
Thumbs.db

# IDE
.idea/
.vscode/
*.swp
*.swo
*~

# Docker
.docker/

# Per-app configuration (generated by init.sh)
.env
EOF

cd "$TARGET_DIR"

# ── Write .env ──────────────────────────────────────────────
cat > .env <<EOF
# Generated by init.sh — customize as needed
APP_NAME=$APP_NAME
GIT_REPO_BASE=https://github.com/natanbs
REGISTRY_URL=$REGISTRY_URL
REGISTRY_PORT=$REGISTRY_PORT
REGISTRY_CLUSTER_URL=k3d-reg
REGISTRY_CLUSTER_PORT=5000
K8S_NAMESPACE=$K8S_NAMESPACE
CONTAINER_PORT=$CONTAINER_PORT
EOF

info "Wrote .env with project defaults"

# ── Scaffold Dockerfile ─────────────────────────────────────
case "$DOCKERFILE_TYPE" in
  go)
    cat > Dockerfile <<'DOCKER'
FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY main.go .
RUN go build -o server main.go

FROM alpine:3.21
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 8080
CMD ["./server"]
DOCKER
    cat > main.go <<'GO'
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello from Go!")
	})
	http.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
	http.HandleFunc("/readyz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	})
	http.ListenAndServe(":8080", nil)
}

func port() string {
	return "8080"
}
GO
    info "Scaffolded Go Dockerfile + main.go"
    ;;

  python|py)
    cat > Dockerfile <<'DOCKER'
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
EXPOSE ${CONTAINER_PORT}
CMD ["python", "app.py"]
DOCKER
    cat > requirements.txt <<'EOF'
flask==3.0.0
EOF
    cat > app.py <<'EOF'
from flask import Flask
app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello from Python!"

@app.route("/healthz")
def healthz():
    return "ok", 200

@app.route("/readyz")
def readyz():
    return "ok", 200

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080)
EOF
    info "Scaffolded Python Flask Dockerfile + app.py"
    ;;

  node)
    cat > Dockerfile <<'DOCKER'
FROM node:20-alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY server.js .
EXPOSE ${CONTAINER_PORT}
CMD ["node", "server.js"]
DOCKER
    cat > package.json <<'EOF'
{
  "name": "my-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "start": "node server.js"
  }
}
EOF
    cat > server.js <<'EOF'
const http = require("http");
const port = process.env.PORT || 8080;
const server = http.createServer((req, res) => {
  if (req.url === "/healthz" || req.url === "/readyz") {
    res.writeHead(200);
    return res.end("ok");
  }
  res.writeHead(200, { "Content-Type": "text/plain" });
  res.end("Hello from Node.js!");
});
server.listen(port, () => console.log(`Listening on ${port}`));
EOF
    info "Scaffolded Node.js Dockerfile + server.js"
    ;;

  none|*)
    info "No Dockerfile scaffolded (add your own)"
    ;;
esac

git init
git add .
git commit -m "Initial scaffold" >/dev/null

# ── Ensure namespace exists ─────────────────────────────────
if command -v kubectl &>/dev/null && kubectl cluster-info 2>/dev/null >/dev/null; then
  kubectl create namespace "$K8S_NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null
  info "Ensured namespace '$K8S_NAMESPACE' exists on cluster"
else
  warn "No cluster reachable — skipping namespace creation"
fi

# ── Run build if requested ───────────────────────────────────
if [ "$RUN_BUILD" = true ]; then
  echo
  step "Building Docker image"
  curl -sL https://github.com/natanbs/gitops-template/raw/main/build.sh \
    | bash -s -- --app-name "$APP_NAME" --image-tag "$IMAGE_TAG"
  BUILD_STATUS=$?

  if [ "$BUILD_STATUS" -ne 0 ]; then
    warn "Build failed with exit code $BUILD_STATUS"
  fi

  if [ "$RUN_DEPLOY" = true ]; then
    step "Deploying to Kubernetes"
    curl -sL https://github.com/natanbs/gitops-template/raw/main/build.sh \
      | bash -s -- --app-name "$APP_NAME" --image-tag "$IMAGE_TAG" --auto-deploy
    DEPLOY_STATUS=$?
    if [ "$DEPLOY_STATUS" -ne 0 ]; then
      warn "Deploy failed with exit code $DEPLOY_STATUS"
    fi
  fi
fi

# ── Summary ──────────────────────────────────────────────────
echo
step() { printf "\n${CYAN}=== %s ===${NC}\n" "$*"; }
step "Scaffold complete"
echo
echo "  Directory: $TARGET_DIR"
echo "  App name:  $APP_NAME"
echo "  Registry:  $REGISTRY_URL:$REGISTRY_PORT"
echo "  Namespace: $K8S_NAMESPACE"
echo
if [ "$RUN_BUILD" = false ]; then
  echo "Next steps:"
  echo "  cd ../$APP_NAME"
  echo '  curl -sL https://github.com/natanbs/gitops-template/raw/main/build.sh \'
  echo "    | bash -s -- --app-name $APP_NAME --image-tag v1.0"
  echo '  curl -sL https://github.com/natanbs/gitops-template/raw/main/build.sh \'
  echo "    | bash -s -- --app-name $APP_NAME --image-tag v1.0 --auto-deploy"
fi
echo
